import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Command } from 'cmdk'
import getPosts from './api/getPosts'
import React from 'react'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

function CommandMenu({ posts: allPosts }: { posts: any }) {
  const [open, setOpen] = React.useState(false)
  React.useEffect(() => {
    const downHandler = (e: any) => {
      if (e.key === 'k' && e.metaKey) {
        setOpen((open) => !open);
      }
    }
    window.addEventListener('keydown', downHandler)
    return () => {
      window.removeEventListener('keydown', downHandler)
    }
  }, [])
  // return a command menu with all posts in pages/posts
  return (
    <Command.Dialog open={open} onOpenChange={setOpen} label="Command Menu" className='fixed top-0 left-0 right-0 m-auto w-[45vw] mt-[20vh] bg-slate-600 p-4 rounded-lg'>
      <Command.Input className='w-full bg-slate-600 rounded-lg border p-1 border-solid border-black mb-2' autoFocus placeholder="Search for posts..." />
      <Command.List className='text-white'>
        <Command.Empty >No results found.</Command.Empty>
        {/* create an item for every post */}
        {allPosts.map((post: any) => (
          <Command.Item key={post.link} className='m-2 '><a href={`/posts/${post.link}`}>{post.title}</a></Command.Item>
        ))}
      </Command.List>
    </Command.Dialog>
  )
}

export default function Home({ allPosts }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='relative'>
        <CommandMenu posts={allPosts} />
        <main className={styles.main}>
          <div className={styles.description}>
            <p>
              Get started by editing&nbsp;
              <code className={styles.code}>pages/index.tsx</code>
            </p>
            <div>
              <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                By{' '}
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  className={styles.vercelLogo}
                  width={100}
                  height={24}
                  priority
                />
              </a>
            </div>
          </div>

          <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
            <div className={styles.thirteen}>
              <Image
                src="/thirteen.svg"
                alt="13"
                width={40}
                height={31}
                priority
              />
            </div>
          </div>

          <div className={styles.grid}>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Docs <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Find in-depth information about Next.js features and&nbsp;API.
              </p>
            </a>

            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Learn <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Learn about Next.js in an interactive course with&nbsp;quizzes!
              </p>
            </a>

            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Templates <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Discover and deploy boilerplate example Next.js&nbsp;projects.
              </p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Deploy <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Instantly deploy your Next.js site to a shareable URL
                with&nbsp;Vercel.
              </p>
            </a>
          </div>
        </main>
      </div>
    </>
  )
}

// fetch all posts from pages/posts
export async function getStaticProps() {
  // use getPosts api to get all posts
  const posts = getPosts()
  // map all posts to get their titles and names
  const allPosts = posts.map((post: any) => {
    const component = require(`./posts/${post}`)
    return {
      link: post.replace('.tsx', ''),
      title: component.title,
    }
  })
  return {
    props: { allPosts },
  }
}